name: Deploy example page

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/deploy.yml"
      - "sdk/hooks/**/*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Build
        run: |
          cd sdk/hooks
          yarn install
          yarn build --base /examples

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./sdk/hooks/dist
